version: '3.8'

services:
  db:
    build:
      context: . # указывает на дерикторию, где находится докерфайл
      dockerfile: Dockerfile_db
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: . # указывает на дерикторию, где находится докерфайл
      dockerfile: Dockerfile_web
    container_name: flask_app
    command: python3 app.py
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/main_db
    ports:
      - "8080:8080"
    depends_on:
      - db